### ISSUE TITLE
AMP enabled info spamming the console

### ISSUE THREAD

**Issue by Sirosky** [muslll/neosr#1]
Not sure why this is happening, but wanted to report as a potential bug. (It's driving me nuts). I tried figuring out where the AMP printing code is located but no such luck. =/

![image](https://github.com/muslll/neosr/assets/2752448/26861a65-052a-45f3-af2e-373f002b6a2f)

**Comment by muslll** [comment]
Thanks for reporting. Fixed on this [commit](https://github.com/muslll/neosr/commit/c49de77db1b1c878881ddefc33363d24e58812d0).
