### ISSUE TITLE
Exiting early doesn't save latest training state

### ISSUE THREAD

**Issue by awused** [muslll/neosr#12]
If you exit early it saves the latest model (`net_g_latest` and `net_d_latest`) but not the latest training state, so when you resume training it restarts from the latest regular checkpoint.

**Comment by muslll** [comment]
Hi, sorry for the late reply. This is a known issue that, unfornatelly, is more complicated to solve than it seems. Hopefully I can take a look at it in the future. Feel free to send PRs regarding the issue.
