### ISSUE TITLE
Print file path that causes read error upon dataloader crash

### ISSUE THREAD

**Issue by Kim2091** [muslll/neosr#15]
This would be extremely helpful for troubleshooting a large dataset. I just had an issue where I was getting errors in my dataset about a corrupted file, and it turns out it was trying to read a my meta_info file as an image all along. I was only able to diagnose this after hacking together a modified dataloader script.

I will share my code if desired, but it is not pretty.

**Comment by muslll** [comment]
> I will share my code if desired, but it is not pretty.
Please do, I can take a look at some point.
