### ISSUE TITLE
Feature request: allow toggling attention implementation via options

### ISSUE THREAD

**Issue by Mikewando** [muslll/neosr#20]
Some networks have been modified from their official versions to use `scaled_dot_product_attention`. I understand this has some benefits, but for the time being it also prevents onnx exporting. There's been some discussion on [discord](https://discord.com/channels/547949405949657098/549520096612188181/1161219871162519612) about adding the ability to toggle (I think initially to turn it _on_ for the archs which have off at the moment) and the primary concern about adding the option as I understand it is breaking compatibility with e.g. ChaiNNer. It seems like with an agreed upon [convention](https://discord.com/channels/547949405949657098/549520096612188181/1161279981645746227) it should be possible to support both. I'm just opening this issue to track the progress of the topic more easily than finding discord links every time.

**Comment by muslll** [comment]
Hi! This has been requested by other people as well. I agree, there should be an option to toggle flash attention. I'll be working on it and reporting it here once finished.
