### ISSUE TITLE
train.py throws an error, unable to proceed to training.

### ISSUE THREAD

**Issue by youzrneym** [muslll/neosr#24]
Here's the output on the terminal.

(venv) [username@archlinux neosr]$ python train.py -opt train_realesrgan.yml
Traceback (most recent call last):
  File "/home/username/neosr/train.py", line 241, in <module>
    train_pipeline(root_path)
  File "/home/username/neosr/train.py", line 101, in train_pipeline
    opt, args = parse_options(root_path, is_train=True)
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/username/neosr/neosr/utils/options.py", line 163, in parse_options
    opt['dist'] = False
    ~~~^^^^^^^^
TypeError: 'str' object does not support item assignment



Python 3.11.7
Latest pytorch
Cuda 12.1

**Comment by muslll** [comment]
Hello, cannot reproduce your error. Usually those errors are due to improper env, so I'd recommend you redo it using poetry (as you're on Arch), as written in the readme. Also, make sure your config file follows the [template](https://github.com/muslll/neosr/blob/master/options/train_realesrgan.yml).

**Comment by youzrneym** [comment]
Same error even with poetry, here's the output.



[username@archlinux neosr]$ ~/.local/bin/poetry shell
Spawning shell within /home/username/neosr/.venv
[username@archlinux neosr]$ . /home/username/neosr/.venv/bin/activate
(neosr-py3.11) [username@archlinux neosr]$ python train.py -opt train_realesrgan.yml
Traceback (most recent call last):
  File "/home/username/neosr/train.py", line 241, in <module>
    train_pipeline(root_path)
  File "/home/username/neosr/train.py", line 101, in train_pipeline
    opt, args = parse_options(root_path, is_train=True)
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/username/neosr/neosr/utils/options.py", line 163, in parse_options
    opt['dist'] = False
    ~~~^^^^^^^^
TypeError: 'str' object does not support item assignment



I'm using the default config btw, i double checked my datasets paths as per instructions, without special characters.

**Comment by youzrneym** [comment]
Just needed to install "packaging" and it solved my issue. 
Works on a regular venv too.
