### ISSUE TITLE
incorrect conversion to grayscale

### ISSUE THREAD

**Issue by umzi2** [muslll/neosr#28]
https://github.com/muslll/neosr/blob/f2a2be9f45f1dd53b509d0adec16316ccf2ad22c/neosr/data/single_dataset.py#L51
in this piece of code you have an error, you are converting float32 to int8 directly, i.e. the output is int 0-1
`img_lq = Image.fromarray(img_lq.astype(np.uint8))` if we add multiplication by 255 here
`img_lq = np.array(img_lq, dtype=np.float32)` and here division by 255

then the output will be a correct output in the range from 0 to 1
otherwise, everything below 1 will be 0 and 1 will be equal to 1

but this is a straightforward solution, I just want to report a bug

**Comment by muslll** [comment]
Fixed on [#1ddad19](https://github.com/muslll/neosr/commit/1ddad19edb3702e7cce82a13324670019de4d311), thanks for reporting.
