### ISSUE TITLE
Validation doesn't appear to be working.

### ISSUE THREAD

**Issue by Sirosky** [muslll/neosr#3]
As the title says, even with validation on in the config, it doesn't seem to do anything. 

YML config for reference: https://pastebin.com/y6ZKPqta.

**Comment by muslll** [comment]
Indentation is wrong. Look at the [template file](https://github.com/muslll/neosr/blob/master/options/train_omnisr.yml#L27), one of the `val` must be inside `datasets`, and the other one outside of it. 
It is on my todo list to switch all configs to TOML instead, to avoid such issues. If you fix the indentation, it should work just fine.
