### ISSUE TITLE
Models and states saving/loading issue

### ISSUE THREAD

**Issue by terrainer** [muslll/neosr#37]
The latest update introduces a bug where models and states are saved as "{current_iter}.0.pth" and {current_iter}.0.state, the models are being looked for with the new naming scheme, but the state is still loaded with the expectation that there is no ".0", and returns an error as it cannot find "{current_iter}.state".

Tested this on a clean neosr install.

**Comment by muslll** [comment]
[Fixed](https://github.com/muslll/neosr/commit/f88655bd51d8e1dc68c4c32fcbaf124a978b6759), thanks for reporting.
