### ISSUE TITLE
Huge performance drop after update

### ISSUE THREAD

**Issue by VandersonQk** [muslll/neosr#54]
Today I updated neosr and noticed a huge drop in performance.
- RGT: from 2.9 it/s to 1.6 it/s
- Swinir_small: from 6.6 it/s to 2.3 it/s

I reversed commit by commit and found that the 2dcafe4 (Change no_grad -> inference_mode) was causing it. 

Was it supposed to happen?

My setup: ubuntu 23.04, rtx 4090, torch 2.2.0
Train config: RGT and swinir_small, both otf and paired, amp + bfloat16 enabled.

Before update (RGT):
![image](https://github.com/muslll/neosr/assets/7416219/e966963e-ba01-4d88-8298-9a75dbc44306)

After update:
![image](https://github.com/muslll/neosr/assets/7416219/aa58e3bb-701e-4e9c-ac4c-7f81d8af6470)

**Comment by muslll** [comment]
Hi @VandersonQk! I'm looking into this issue this week, I'll let you know once it's solved :+1:

**Comment by muslll** [comment]
Fixed. Please update :+1:

**Comment by VandersonQk** [comment]
Thanks. RGT is working properly again and it's faster than before!
