### ISSUE TITLE
`train_realesrgan.yml` is named "train_esrgan"

### ISSUE THREAD

**Issue by RunDevelopment** [muslll/neosr#58]
https://github.com/muslll/neosr/blob/ff23dc06ece18589c93755f8fac36416ab70ca71/options/train_realesrgan.yml#L2C7-L2C19

This is because the file was initially `train_esrgan.yml` and later renamed. Seems like you forgot to update the internal name of the config.

**Comment by muslll** [comment]
This is actually on purpose. The ESRGAN and Real-ESRGAN network is the same, what differs is the training. Specifically the high-order degradations and the unet with spectral normalization. So I thought it would be a good idea to keep it with a generic name instead.
Although the file is named realesrgan anyway, which is inconsistent. I'll just rename the file itself, thanks for the suggestion :+1:
