### ISSUE TITLE
imwrite raise IOError when trying to write an image where the filename contains unicode characters

### ISSUE THREAD

**Issue by mogrol** [muslll/neosr#59]
OpenCV (currently) doesn't support writing to paths which contain Unicode characters. Mentioned here: [https://github.com/opencv/opencv-python/issues/211](https://github.com/opencv/opencv-python/issues/211) and here: [https://github.com/opencv/opencv/issues/4292](https://github.com/opencv/opencv/issues/4292)

**Comment by mogrol** [comment]
Fix:

--- a/neosr/utils/img_util.py
+++ b/neosr/utils/img_util.py
@@ -159,8 +159,10 @@ def imwrite(img, file_path, params=None, auto_mkdir=True):
     if auto_mkdir:
         dir_name = os.path.abspath(os.path.dirname(file_path))
         os.makedirs(dir_name, exist_ok=True)
-    ok = cv2.imwrite(file_path, img, params)
-    if not ok:
+    #ok = cv2.imwrite(file_path, img, params)
+    try:
+        cv2.imencode(os.path.splitext(file_path)[1], img)[1].tofile(file_path)
+    except Exception:
         raise IOError('Failed in writing images.')

**Comment by muslll** [comment]
Thanks, fixed on [b556449](https://github.com/muslll/neosr/commit/b5564494c3f5a92a39e5bdb859129eeb2211979e) :+1:
