### ISSUE TITLE
Mismatched resume state issue

### ISSUE THREAD

**Issue by Kim2091** [muslll/neosr#72]
When resuming training from a manually specified resume state, if the name of the model at the top of the config is mismatched with the resume state it throws an ambiguous error about the yml file being missing. It'd be good to have a proper error message for this condition

**Comment by muslll** [comment]
Fixed in [dc39231](https://github.com/muslll/neosr/commit/dc3923166ccd45ff677bafbbcf3e9b0b5b8fff9b).
