### ISSUE TITLE
Python version problem

### ISSUE THREAD

**Issue by seanko29** [muslll/neosr#77]
Thank you for your work.
I want to test this work in python 3.10 since I am not a sudo-user in which I dont have the authority to change the python version myself...

Is there any way to run your codes in python 3.10 ? 
If there are any limitations in some packages, I will try to adjust it. 

Thank you.

**Comment by muslll** [comment]
Hi seanko. I haven't tested py3.10, so I can't say for sure it will work. However, it probably will work because currently neosr does not make use of any py3.12-specific feature (although this will change in the next months).
If you give it a try and it doesn't work, let me know what issue you encounter and I can help you.

**Comment by seanko29** [comment]
> Hi seanko. I haven't tested py3.10, so I can't say for sure it will work. However, it probably will work because currently neosr does not make use of any py3.12-specific feature (although this will change in the next months). If you give it a try and it doesn't work, let me know what issue you encounter and I can help you.

Hey muslll, It seems to work with python 3.10. Thank you! Did not install the poetry package though. It also works with custom models that are not provided here.
However, there seems to be an error when I turn on the validation mode. I wanted to train and validate at the same time on train_span.yml. 
I get the following error. 

File "/home/sean/ACCV/neosr/neosr/data/degradations.py", line 11, in <module>
    rng = rng()
  File "/home/sean/ACCV/neosr/neosr/utils/rng.py", line 8, in rng
    opt, args = parse_options(root_path, is_train=True)
  File "/home/sean/ACCV/neosr/neosr/utils/options.py", line 176, in parse_options
    opt = yaml_load(args.opt)
  File "/home/sean/ACCV/neosr/neosr/utils/options.py", line 51, in yaml_load
    return yaml.load(f, Loader=ordered_yaml()[0])
  File "/home/sean/myenvv/lib/python3.10/site-packages/yaml/__init__.py", line 81, in load
    return loader.get_single_data()
  File "/home/sean/myenvv/lib/python3.10/site-packages/yaml/constructor.py", line 49, in get_single_data
    node = self.get_single_node()
  File "yaml/_yaml.pyx", line 673, in yaml._yaml.CParser.get_single_node
  File "yaml/_yaml.pyx", line 687, in yaml._yaml.CParser._compose_document
  File "yaml/_yaml.pyx", line 731, in yaml._yaml.CParser._compose_node
  File "yaml/_yaml.pyx", line 847, in yaml._yaml.CParser._compose_mapping_node
  File "yaml/_yaml.pyx", line 860, in yaml._yaml.CParser._parse_next_event
yaml.parser.ParserError: while parsing a block mapping
  in "options/train_span.yml", line 2, column 1
did not find expected key

The following error occurs when I turn on these in the yml file. 

 val:
   name: val_1
   type: paired 
   dataroot_gt: /home/sean/data/DF2K/DIV2K_valid_HR
   dataroot_lq: /home/sean/data/DF2K/DIV2K_valid_LR_bicubic/X2
   filename_tmpl: '{}x2'
   io_backend:
     type: disk
val:
 val_freq: 1000
 save_img: true
 save_tb: true
 tile: -1 # 200
 metrics:
   psnr:
     type: calculate_psnr
   ssim:
     type: calculate_ssim
   dists:
     type: calculate_dists
     better: lower

Is it not possible to train and validate at the same time on a single train.yml file? I believe that we can on the top of the head since neosr has a very similar structure with basicsr...  I just could not catch the error :( 

Thank you in advanced.

**Comment by seanko29** [comment]
woops, I think during copy pasting, the indentation flew away. 
I fixed the problem that there is two "val" in the yml file and their indentations were different and I did not take into consideration.  (baiscally, indentation problem).

Thank you!!
