### ISSUE TITLE
model zoo

### ISSUE THREAD

**Issue by ttys0001** [muslll/neosr#79]
Thank you to the author, this repository is very valuable. 

I would like to ask if it is possible to add a model zoo in the future, which can include pretrained models of all supported models for direct testing?

**Comment by muslll** [comment]
Hi @ttys0001, thank you. For the model zoo, please check out [OpenModelDB](https://openmodeldb.info/). Almost all pretrained models for the networks are there. If you have any other questions let me know :+1:
